apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: viniciusmaltaaraujo/api-produto:versao-teste
        resources: {}
        ports:
        - containerPort: 80
        env:
          - name: Mongo__Host
            value: mongo-service
          - name: Mongo__User
            value: mongodbuser
          - name: Mongo__Password
            value: mongodbpwd
          - name: Mongo__Port
            value: "27017"
          - name: Mongo_DataBase
            value: admin
